services:
  sharenote:
    container_name: sharenote
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8086
    # ports:
    #   - "8086:8086"
    volumes:
      - "./static:/sharenote-py/static"
